# Generated by Django 3.2 on 2021-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrecord',
            name='authentic_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsrecord',
            name='fake_count',
            field=models.IntegerField(default=0),
        ),
    ]
